Repository OCA/hr-holidays, pull requests merged in 2021-04, with the labels that each got.

#19 [14.0] [mig] hr_holidays_public
  hr_holidays_public/README.rst
  hr_holidays_public/__init__.py
  hr_holidays_public/__manifest__.py
  hr_holidays_public/data/data.xml
  hr_holidays_public/i18n/ar.po
  hr_holidays_public/i18n/de.po
  hr_holidays_public/i18n/es.po
  hr_holidays_public/i18n/fi.po
  hr_holidays_public/i18n/fr.po
  hr_holidays_public/i18n/hr.po
  hr_holidays_public/i18n/hr_HR.po
  hr_holidays_public/i18n/hr_holidays_public.pot
  hr_holidays_public/i18n/it.po
  hr_holidays_public/i18n/nl_NL.po
  hr_holidays_public/i18n/pl.po
  hr_holidays_public/i18n/pt_BR.po
  hr_holidays_public/i18n/ro.po
  hr_holidays_public/i18n/sl.po
  hr_holidays_public/models/__init__.py
  hr_holidays_public/models/hr_holidays_public.py
  hr_holidays_public/models/hr_leave.py
  hr_holidays_public/models/hr_leave_type.py
  hr_holidays_public/models/resource_calendar.py
  hr_holidays_public/readme/CONFIGURE.rst
  hr_holidays_public/readme/CONTRIBUTORS.rst
  hr_holidays_public/readme/DESCRIPTION.rst
  hr_holidays_public/readme/ROADMAP.rst
  hr_holidays_public/readme/USAGE.rst
  hr_holidays_public/security/ir.model.access.csv
  hr_holidays_public/static/description/icon.png
  hr_holidays_public/static/description/icon.svg
  hr_holidays_public/static/description/index.html
  hr_holidays_public/tests/__init__.py
  hr_holidays_public/tests/test_holidays_calculation.py
  hr_holidays_public/tests/test_holidays_public.py
  hr_holidays_public/views/hr_holidays_public_view.xml
  hr_holidays_public/views/hr_leave_type.xml
  hr_holidays_public/wizards/__init__.py
  hr_holidays_public/wizards/holidays_public_next_year_wizard.py
  hr_holidays_public/wizards/holidays_public_next_year_wizard.xml
  setup/hr_holidays_public/odoo/addons/hr_holidays_public
  setup/hr_holidays_public/setup.py
Labels: approved, bot is merging ⏳

#5 [13.0][MIG] hr_holidays_leave_auto_approve
  hr_holidays_leave_auto_approve/README.rst
  hr_holidays_leave_auto_approve/__init__.py
  hr_holidays_leave_auto_approve/__manifest__.py
  hr_holidays_leave_auto_approve/i18n/ar.po
  hr_holidays_leave_auto_approve/i18n/cs_CZ.po
  hr_holidays_leave_auto_approve/i18n/de.po
  hr_holidays_leave_auto_approve/i18n/es.po
  hr_holidays_leave_auto_approve/i18n/fa.po
  hr_holidays_leave_auto_approve/i18n/fr.po
  hr_holidays_leave_auto_approve/i18n/fr_CH.po
  hr_holidays_leave_auto_approve/i18n/hr.po
  hr_holidays_leave_auto_approve/i18n/hr_HR.po
  hr_holidays_leave_auto_approve/i18n/hr_holidays_leave_auto_approve.pot
  hr_holidays_leave_auto_approve/i18n/nl.po
  hr_holidays_leave_auto_approve/i18n/nl_NL.po
  hr_holidays_leave_auto_approve/i18n/sl.po
  hr_holidays_leave_auto_approve/models/__init__.py
  hr_holidays_leave_auto_approve/models/hr_leave.py
  hr_holidays_leave_auto_approve/models/hr_leave_type.py
  hr_holidays_leave_auto_approve/readme/CONFIGURE.rst
  hr_holidays_leave_auto_approve/readme/CONTRIBUTORS.rst
  hr_holidays_leave_auto_approve/readme/DESCRIPTION.rst
  hr_holidays_leave_auto_approve/static/description/icon.png
  hr_holidays_leave_auto_approve/static/description/index.html
  hr_holidays_leave_auto_approve/tests/__init__.py
  hr_holidays_leave_auto_approve/tests/test_hr_holidays_leave_auto_approve.py
  hr_holidays_leave_auto_approve/views/hr_holidays_status.xml
Labels: approved, bot is merging ⏳, ready to merge

#22 [13.0][FIX] hr_holidays_public: Fix number_of_days in leaves when contain holiday in leave and hour start from resource calendar in 00:01
  hr_holidays_public/models/hr_holidays_public.py
  hr_holidays_public/models/resource_calendar.py
Labels: bot is merging ⏳

#24 [14.0][FIX] hr_holidays_public: Fix number_of_days in leaves when contain holiday in leave and hour start from resource calendar in 00:01
  hr_holidays_public/models/hr_holidays_public.py
  hr_holidays_public/models/resource_calendar.py
Labels: approved, bot is merging ⏳

#25 [13.0][FIX] hr_holidays_public: Prevent error in leave form without employee set yet
  hr_holidays_public/models/resource_calendar.py
Labels: bot is merging ⏳

#26 [14.0][FIX] hr_holidays_public: Prevent error in leave form without employee set yet
  hr_holidays_public/models/resource_calendar.py
Labels: approved, bot is merging ⏳

#23 [13.0][FIX] hr_holidays_natural_period: Prevent error in form leave when employee is not set yet.
  hr_holidays_natural_period/models/resource_calendar.py
Labels: approved, bot is merging ⏳
