Repository OCA/hr-holidays, pull requests merged in 2022-01, with the labels that each got.

#36 [14.0][Fix] hr_holiday_public: Work time per day not excluding holidays
  hr_holidays_public/models/hr_leave.py
Labels: approved, bot is merging ⏳

#39 [IMP] Apply copier template
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .t2d.yml
  LICENSE
  README.md
  hr_holidays_leave_repeated/__manifest__.py
  hr_holidays_natural_period/__manifest__.py
  hr_holidays_settings/__manifest__.py
Labels: approved

#37 [13.0][FIX] hr_holidays_natural_period: Fix _exist_interval_in_date() function + Impove tests.
  hr_holidays_natural_period/models/resource_calendar.py
  hr_holidays_natural_period/tests/test_hr_leave.py
Labels: bot is merging ⏳
