Repository OCA/hr-holidays, pull requests merged in 2023-11, with the labels that each got.

#96 [16.0][MIG] hr_holidays_public_city: Migration to 16.0
  hr_holidays_public_city/README.rst
  hr_holidays_public_city/__init__.py
  hr_holidays_public_city/__manifest__.py
  hr_holidays_public_city/i18n/es.po
  hr_holidays_public_city/i18n/hr_holidays_public_city.pot
  hr_holidays_public_city/i18n/it.po
  hr_holidays_public_city/models/__init__.py
  hr_holidays_public_city/models/hr_holidays_public.py
  hr_holidays_public_city/models/hr_leave.py
  hr_holidays_public_city/readme/CONTRIBUTORS.rst
  hr_holidays_public_city/readme/DESCRIPTION.rst
  hr_holidays_public_city/static/description/icon.png
  hr_holidays_public_city/static/description/index.html
  hr_holidays_public_city/tests/__init__.py
  hr_holidays_public_city/tests/test_holidays_calculation.py
  hr_holidays_public_city/tests/test_holidays_public.py
  hr_holidays_public_city/views/hr_holidays_public_view.xml
  setup/hr_holidays_public_city/odoo/addons/hr_holidays_public_city
  setup/hr_holidays_public_city/setup.py
Labels: approved, bot is merging ⏳

#87 [15.0][ADD] hr_holidays_public_overtime
  hr_holidays_public_overtime/README.rst
  hr_holidays_public_overtime/__init__.py
  hr_holidays_public_overtime/__manifest__.py
  hr_holidays_public_overtime/models/__init__.py
  hr_holidays_public_overtime/models/hr_attendance.py
  hr_holidays_public_overtime/readme/CONTRIBUTORS.rst
  hr_holidays_public_overtime/readme/DESCRIPTION.rst
  hr_holidays_public_overtime/readme/USAGE.rst
  hr_holidays_public_overtime/static/description/icon.png
  hr_holidays_public_overtime/static/description/index.html
  hr_holidays_public_overtime/tests/__init__.py
  hr_holidays_public_overtime/tests/test_hr_holidays_public_attendance.py
  setup/hr_holidays_public_overtime/odoo/addons/hr_holidays_public_overtime
  setup/hr_holidays_public_overtime/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#98 [FIX] hr_holidays_public: wrong computation in case resources in different countries
  hr_holidays_public/models/resource_calendar.py
  hr_holidays_public/tests/test_holidays_public.py
Labels: bot is merging ⏳
