Repository OCA/hr-holidays, pull requests merged in 2023-04, with the labels that each got.

#69 [16.0][FIX] - hr_public_holidays: holidays table is not fully visible in form view
  hr_holidays_public/views/hr_holidays_public_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#68 [14.0][FIX] hr_holidays_public: Translatable action
  hr_holidays_public/wizards/holidays_public_next_year_wizard.py
Labels: bot is merging ⏳

#71 [15.0][FIX] hr_holidays_natural_period: Avoid error when saving leave
  hr_holidays_natural_period/demo/hr_leave_type_data.xml
  hr_holidays_natural_period/models/hr_leave_type.py
  hr_holidays_natural_period/tests/test_hr_leave.py
Labels: approved, bot is merging ⏳
