Repository OCA/hr-holidays, pull requests merged in 2024-07, with the labels that each got.

#114 [15.0][FIX] hr_holidays_public: fixed action_validate() override
  hr_holidays_public/models/hr_leave.py
Labels: approved, bot is merging ⏳

#115 [16.0][FIX] hr_holidays_public: fixed action_validate() override
  hr_holidays_public/models/hr_leave.py
Labels: approved

#130 [15.0][FIX] hr_holidays_public*: Use the context employee or the user's employee
  hr_holidays_public/models/hr_leave.py
  hr_holidays_public/tests/test_holidays_public.py
  hr_holidays_public_city/models/hr_leave.py
  hr_holidays_public_city/tests/test_holidays_public.py
Labels: approved, bot is merging ⏳

#67 [ADD] hr_holidays_auto_extend
  hr_holidays_auto_extend/README.rst
  hr_holidays_auto_extend/__init__.py
  hr_holidays_auto_extend/__manifest__.py
  hr_holidays_auto_extend/data/cron.xml
  hr_holidays_auto_extend/data/mail.xml
  hr_holidays_auto_extend/models/__init__.py
  hr_holidays_auto_extend/models/hr_leave.py
  hr_holidays_auto_extend/models/hr_leave_type.py
  hr_holidays_auto_extend/readme/CONTRIBUTORS.rst
  hr_holidays_auto_extend/readme/DESCRIPTION.rst
  hr_holidays_auto_extend/readme/USAGE.rst
  hr_holidays_auto_extend/static/description/icon.png
  hr_holidays_auto_extend/tests/__init__.py
  hr_holidays_auto_extend/tests/test_extend.py
  hr_holidays_auto_extend/views/hr_leave.xml
  hr_holidays_auto_extend/views/hr_leave_type.xml
  setup/hr_holidays_auto_extend/odoo/addons/hr_holidays_auto_extend
  setup/hr_holidays_auto_extend/setup.py
Labels: approved, bot is merging ⏳, stale

#132 [16.0][FIX] hr_holidays_public*: Use the context employee or the user's employee
  hr_holidays_public/models/hr_leave.py
  hr_holidays_public/tests/test_holidays_public.py
  hr_holidays_public_city/models/hr_leave.py
  hr_holidays_public_city/tests/test_holidays_public.py
Labels: approved, ready to merge, bot is merging ⏳

#134 [17.0][FIX] hr_holidays_public*: Use the context employee or the user's employee
  hr_holidays_public/models/hr_leave.py
  hr_holidays_public/tests/test_holidays_calculation.py
  hr_holidays_public/tests/test_holidays_public.py
  hr_holidays_public_city/models/hr_leave.py
  hr_holidays_public_city/tests/test_holidays_public.py
Labels: approved, bot is merging ⏳
