Repository OCA/hr-holidays, pull requests merged in 2024-09, with the labels that each got.

#140 [FIX] [16.0] resource_leaves_geographic: Make leave datetimes aware with user tz
  resource_leaves_geographic/models/resource_calendar.py
Labels: approved, bot is merging ⏳

#136 [16.0] [MIG] hr_holidays_auto_extend: Migration to 16.0
  hr_holidays_auto_extend/README.rst
  hr_holidays_auto_extend/__init__.py
  hr_holidays_auto_extend/__manifest__.py
  hr_holidays_auto_extend/data/cron.xml
  hr_holidays_auto_extend/data/mail.xml
  hr_holidays_auto_extend/i18n/hr_holidays_auto_extend.pot
  hr_holidays_auto_extend/models/__init__.py
  hr_holidays_auto_extend/models/hr_leave.py
  hr_holidays_auto_extend/models/hr_leave_type.py
  hr_holidays_auto_extend/readme/CONTRIBUTORS.rst
  hr_holidays_auto_extend/readme/DESCRIPTION.rst
  hr_holidays_auto_extend/readme/USAGE.rst
  hr_holidays_auto_extend/static/description/icon.png
  hr_holidays_auto_extend/static/description/index.html
  hr_holidays_auto_extend/tests/__init__.py
  hr_holidays_auto_extend/tests/test_extend.py
  hr_holidays_auto_extend/views/hr_leave.xml
  hr_holidays_auto_extend/views/hr_leave_type.xml
  setup/hr_holidays_auto_extend/odoo/addons/hr_holidays_auto_extend
  setup/hr_holidays_auto_extend/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#120 [16.0][MIG] hr_holidays_settings
  hr_holidays_settings/README.rst
  hr_holidays_settings/__init__.py
  hr_holidays_settings/__manifest__.py
  hr_holidays_settings/i18n/ar.po
  hr_holidays_settings/i18n/ca.po
  hr_holidays_settings/i18n/de.po
  hr_holidays_settings/i18n/es.po
  hr_holidays_settings/i18n/fa.po
  hr_holidays_settings/i18n/fi.po
  hr_holidays_settings/i18n/fr.po
  hr_holidays_settings/i18n/hr.po
  hr_holidays_settings/i18n/hr_HR.po
  hr_holidays_settings/i18n/hr_holidays_settings.pot
  hr_holidays_settings/i18n/it.po
  hr_holidays_settings/i18n/nl_NL.po
  hr_holidays_settings/i18n/pt_BR.po
  hr_holidays_settings/i18n/ro.po
  hr_holidays_settings/i18n/sl.po
  hr_holidays_settings/readme/CONTRIBUTORS.rst
  hr_holidays_settings/readme/DESCRIPTION.rst
  hr_holidays_settings/readme/USAGE.rst
  hr_holidays_settings/static/description/icon.png
  hr_holidays_settings/static/description/index.html
  hr_holidays_settings/views/res_config_settings.xml
  setup/hr_holidays_settings/odoo/addons/hr_holidays_settings
  setup/hr_holidays_settings/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#141 [17.0][MIG] hr_holidays_natural_period: Migration to version 17.0
  hr_holidays_natural_period/README.rst
  hr_holidays_natural_period/__init__.py
  hr_holidays_natural_period/__manifest__.py
  hr_holidays_natural_period/demo/hr_leave_type_data.xml
  hr_holidays_natural_period/i18n/ca.po
  hr_holidays_natural_period/i18n/es.po
  hr_holidays_natural_period/i18n/hr.po
  hr_holidays_natural_period/i18n/hr_holidays_natural_period.pot
  hr_holidays_natural_period/i18n/it.po
  hr_holidays_natural_period/models/__init__.py
  hr_holidays_natural_period/models/hr_employee.py
  hr_holidays_natural_period/models/hr_leave.py
  hr_holidays_natural_period/models/hr_leave_allocation.py
  hr_holidays_natural_period/models/hr_leave_type.py
  hr_holidays_natural_period/models/resource_calendar.py
  hr_holidays_natural_period/pyproject.toml
  hr_holidays_natural_period/readme/CONTRIBUTORS.md
  hr_holidays_natural_period/readme/DESCRIPTION.md
  hr_holidays_natural_period/readme/USAGE.md
  hr_holidays_natural_period/static/description/icon.png
  hr_holidays_natural_period/static/description/index.html
  hr_holidays_natural_period/tests/__init__.py
  hr_holidays_natural_period/tests/test_hr_leave.py
Labels: approved, bot is merging ⏳

#116 [17.0][FIX] hr_holidays_public: fixed action_validate() override
  hr_holidays_public/models/hr_leave.py
Labels: bot is merging ⏳
