Repository OCA/hr-holidays, pull requests merged in 2024-05, with the labels that each got.

#119 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  hr_holidays_public/models/hr_leave.py
Labels: help wanted, needs review, bot is merging ⏳

#70 [15.0][ADD] hr_holidays_leave_self_approve
  hr_holidays_leave_self_approve/README.rst
  hr_holidays_leave_self_approve/__init__.py
  hr_holidays_leave_self_approve/__manifest__.py
  hr_holidays_leave_self_approve/models/__init__.py
  hr_holidays_leave_self_approve/models/hr_leave.py
  hr_holidays_leave_self_approve/readme/CONFIGURE.rst
  hr_holidays_leave_self_approve/readme/CONTRIBUTORS.rst
  hr_holidays_leave_self_approve/readme/DESCRIPTION.rst
  hr_holidays_leave_self_approve/tests/__init__.py
  hr_holidays_leave_self_approve/tests/test_hr_holidays_leave_self_approve.py
  setup/hr_holidays_leave_self_approve/odoo/addons/hr_holidays_leave_self_approve
  setup/hr_holidays_leave_self_approve/setup.py
Labels: approved, bot is merging ⏳

#118 [17.0][MIG] hr_holidays_public_city: Migration to 17.0
  hr_holidays_public_city/README.rst
  hr_holidays_public_city/__init__.py
  hr_holidays_public_city/__manifest__.py
  hr_holidays_public_city/i18n/es.po
  hr_holidays_public_city/i18n/hr_holidays_public_city.pot
  hr_holidays_public_city/i18n/it.po
  hr_holidays_public_city/models/__init__.py
  hr_holidays_public_city/models/hr_holidays_public.py
  hr_holidays_public_city/models/hr_leave.py
  hr_holidays_public_city/pyproject.toml
  hr_holidays_public_city/readme/CONTRIBUTORS.md
  hr_holidays_public_city/readme/DESCRIPTION.md
  hr_holidays_public_city/static/description/icon.png
  hr_holidays_public_city/static/description/index.html
  hr_holidays_public_city/tests/__init__.py
  hr_holidays_public_city/tests/test_holidays_calculation.py
  hr_holidays_public_city/tests/test_holidays_public.py
  hr_holidays_public_city/views/hr_holidays_public_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#110 [16.0] hr_holidays_public: Deprecate use of employee_id in favour of partner_id
  hr_holidays_public/models/hr_holidays_public.py
  hr_holidays_public_city/models/hr_holidays_public.py
Labels: approved, bot is merging ⏳

#117 [16.0][FIX] hr_holidays_natural_period: Recalculate the duration value on creation
  hr_holidays_natural_period/models/hr_leave.py
  hr_holidays_natural_period/models/hr_leave_type.py
Labels: bot is merging ⏳
