Repository OCA/hr-holidays, pull requests merged in 2025-03, with the labels that each got.

#168 [17.0][FIX] hr_holidays_natural_period: Define the correct number of days in some use cases
  hr_holidays_natural_period/models/resource_calendar.py
  hr_holidays_natural_period/tests/test_hr_leave.py
Labels: bot is merging ⏳

#154 [17.0][MIG] hr_holidays_settings: Migration to 17.0
  hr_holidays_settings/README.rst
  hr_holidays_settings/__init__.py
  hr_holidays_settings/__manifest__.py
  hr_holidays_settings/i18n/ar.po
  hr_holidays_settings/i18n/ca.po
  hr_holidays_settings/i18n/de.po
  hr_holidays_settings/i18n/es.po
  hr_holidays_settings/i18n/fa.po
  hr_holidays_settings/i18n/fi.po
  hr_holidays_settings/i18n/fr.po
  hr_holidays_settings/i18n/hr.po
  hr_holidays_settings/i18n/hr_HR.po
  hr_holidays_settings/i18n/hr_holidays_settings.pot
  hr_holidays_settings/i18n/it.po
  hr_holidays_settings/i18n/nl_NL.po
  hr_holidays_settings/i18n/pt_BR.po
  hr_holidays_settings/i18n/ro.po
  hr_holidays_settings/i18n/sl.po
  hr_holidays_settings/pyproject.toml
  hr_holidays_settings/readme/CONTRIBUTORS.md
  hr_holidays_settings/readme/DESCRIPTION.md
  hr_holidays_settings/readme/USAGE.md
  hr_holidays_settings/static/description/icon.png
  hr_holidays_settings/static/description/index.html
  hr_holidays_settings/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#165 [17.0][FIX] hr_leave_custom_hour_interval: fix compute_hour functions
  hr_leave_custom_hour_interval/models/hr_leave.py
Labels: approved, bot is merging ⏳

#169 [17.0][FIX] hr_holidays_natural_period: _get_duration handle modified request_unit
  hr_holidays_natural_period/README.rst
  hr_holidays_natural_period/models/hr_employee.py
  hr_holidays_natural_period/models/hr_leave.py
  hr_holidays_natural_period/readme/CONTRIBUTORS.md
  hr_holidays_natural_period/static/description/index.html
Labels: approved, bot is merging ⏳
