Repository OCA/hr-holidays, pull requests merged in 2025-05, with the labels that each got.

#143 [14.0][ADD] hr_holidays_security: New module
  hr_holidays_security/README.rst
  hr_holidays_security/__init__.py
  hr_holidays_security/__manifest__.py
  hr_holidays_security/i18n/es.po
  hr_holidays_security/i18n/hr_holidays_security.pot
  hr_holidays_security/models/__init__.py
  hr_holidays_security/models/hr_leave.py
  hr_holidays_security/models/hr_leave_allocation.py
  hr_holidays_security/models/ir_actions_act_window.py
  hr_holidays_security/readme/CONTEXT.md
  hr_holidays_security/readme/CONTRIBUTORS.md
  hr_holidays_security/readme/DESCRIPTION.md
  hr_holidays_security/readme/USAGE.md
  hr_holidays_security/security/security.xml
  hr_holidays_security/static/description/icon.png
  hr_holidays_security/static/description/index.html
  hr_holidays_security/tests/__init__.py
  hr_holidays_security/tests/test_hr_holidays_security.py
  hr_holidays_security/views/hr_leave_allocation_views.xml
  hr_holidays_security/views/hr_leave_views.xml
  setup/hr_holidays_security/odoo/addons/hr_holidays_security
  setup/hr_holidays_security/setup.py
Labels: approved, bot is merging ⏳

#189 [14.0][FIX] hr_holidays_security: Allow a user with the All Approver permission to be able to select any employee in allocations
  hr_holidays_security/views/hr_leave_allocation_views.xml
Labels: approved, ready to merge, merged 🎉

#192 [16.0][FIX+IMP] hr_holidays_natural_period: Hide Half day option in leaves if natural_day is selected + natural_day_half_day option
  hr_holidays_natural_period/README.rst
  hr_holidays_natural_period/__manifest__.py
  hr_holidays_natural_period/models/hr_leave.py
  hr_holidays_natural_period/models/hr_leave_type.py
  hr_holidays_natural_period/readme/DESCRIPTION.rst
  hr_holidays_natural_period/readme/USAGE.rst
  hr_holidays_natural_period/static/description/index.html
  hr_holidays_natural_period/tests/test_hr_leave.py
  hr_holidays_natural_period/views/hr_leave_views.xml
  hr_holidays_natural_period_public/__manifest__.py
  hr_holidays_natural_period_public/tests/test_hr_holidays_natural_period_public.py
Labels: bot is merging ⏳

#194 [18.0][FIX] hr_holidays_public: Fix _get_durations() multi-record
  hr_holidays_public/models/hr_leave.py
Labels: approved, bot is merging ⏳
